# Azure DevOps Pipeline for Sec1 Security Extension
# Copy this file to your GitHub repo root as: azure-pipelines.yml

trigger:
- main
- develop

pool:
  vmImage: 'ubuntu-latest'

variables:
  # GCP deployment variables - your actual values
  gcpProjectId: 'cve-buster'
  gcpZone: 'us-central1-c'
  gcpVmName: 'playground'  # or 'playground' - choose your target VM
  
  # Sec1 configuration - UPDATE THIS with your actual config ID
  sec1ConfigId: '68c3bffbf6851af8552dad1f'  # Replace with your actual API scan config ID

stages:
- stage: SecurityAndDeploy
  displayName: 'Security Scan and Deploy'
  jobs:
  - job: SecureDeployment
    displayName: 'Sec1 Security Scan and Deployment'
    steps:
    
    # Checkout code
    - checkout: self
      displayName: 'Checkout Source Code'
    
    # Install Docker for deployment
    - task: DockerInstaller@0
      inputs:
        dockerVersion: '20.10.7'
      displayName: 'Install Docker'
    
    # Setup GCP Authentication using Service Account Key
    - task: DownloadSecureFile@1
      name: gcpServiceAccount
      displayName: 'Download GCP Service Account Key'
      inputs:
        secureFile: 'gcp-service-account.json'  # Upload your cve-buster-ea8f39d184da.json file with this name
    
    - script: |
        echo "Setting up GCP authentication..."
        export GOOGLE_APPLICATION_CREDENTIALS=$(gcpServiceAccount.secureFilePath)
        gcloud auth activate-service-account --key-file=$GOOGLE_APPLICATION_CREDENTIALS
        gcloud config set project $(gcpProjectId)
        echo "##vso[task.setvariable variable=GOOGLE_APPLICATION_CREDENTIALS]$GOOGLE_APPLICATION_CREDENTIALS"
      displayName: 'Authenticate with GCP'
    
    # Main Sec1 Security Task - Complete pipeline in one step
    - task: Sec1APISecurity@1
      displayName: 'Sec1 Complete Security Pipeline'
      inputs:
        # Service Connection
        serviceConnection: 'Sec1SecurityServiceConnection'
        
        # Security Scanning Options
        enableSCA: true
        enableSAST: true
        packagePath: 'requirements.txt'  # UPDATE: path to your requirements.txt
        
        # Threshold Configuration (relaxed for testing)
        thresholdCheck: true
        critical: '0'     # Fail on any critical vulnerabilities
        high: '15'        # Allow up to 15 high severity issues (increased from 5)
        medium: '20'      # Allow up to 20 medium severity issues
        low: '50'         # Allow up to 50 low severity issues
        
        # Deployment Configuration
        enableDeployment: true
        deploymentType: 'docker'  # Options: 'docker' or 'script'
        gcpProjectId: '$(gcpProjectId)'
        gcpZone: '$(gcpZone)'
        gcpVmName: '$(gcpVmName)'
        
        # API Scanning Configuration
        enableApiScan: true
        apiScanConfigId: '$(sec1ConfigId)'
        apiScanMode: 'async'        # Use 'sync' to wait for scan completion
        apiScanTimeout: '10'        # Minutes to wait for sync scans
      env:
        # Pass working directory and GCP auth to deployment context
        SEC1_WORKING_DIR: '$(System.DefaultWorkingDirectory)'
        GOOGLE_APPLICATION_CREDENTIALS: '$(GOOGLE_APPLICATION_CREDENTIALS)'
        CLOUDSDK_CORE_PROJECT: '$(gcpProjectId)'

    # Display deployment results
    - script: |
        echo "=== Deployment Summary ==="
        echo "Application URL: $(SEC1_DEPLOYED_APP_URL)"
        echo "API Scan Report ID: $(SEC1_API_SCAN_REPORT_ID)"
        echo "API Scan Report URL: $(SEC1_API_SCAN_REPORT_URL)"
        echo "Deployment Status: $(SEC1_DEPLOYMENT_STATUS)"
      displayName: 'Display Deployment Summary'
      condition: always()